### PR TITLE
Make sure sending_allowed? is respected irrespective of spotlight configuration

### LINKED ISSUE #2226: Sending to sentry is always enabled when using spotlight
### Issue Description

When enabling spotlight, the sentry configuration permits sending events to sentry through `sending_allowed?` regardless of `enabled_environments`.
https://github.com/getsentry/sentry-ruby/blob/5.15.0/sentry-ruby/lib/sentry/configuration.rb#L463

Not setting the `dsn` did not work as a workaround, since `sending_allowed?` also requires a valid DSN before `SpotlightTransport.send_data` is invoked.

### Reproduction Steps

Set `config.spotlight` to `true`, `config.dsn` to a valid DSN, and do not include `config.environment` in `config.enabled_environments`. Trigger an event to be sent threough for example `raise 'test'`.

### Expected Behavior

Events are sent to the spotlight sidecar only, not sentry

### Actual Behavior

Events are sent to both of them

### Ruby Version

3.2.2

### SDK Version

5.15

### Integration and Its Version

Rails 7.0.5.1, sidekiq 6.1

### Sentry Config

Sentry.init do |config|
  # Enable Sentry in production and conditionally in development
  config.environment = 'development'
  config.enabled_environments = ['production']

  config.dsn = DSN

  config.spotlight = true
end

### PR DESCRIPTION
**Pull request by sl0thentr0py**
we need to make a difference between the 'event building' and the 'sending' so I made this more explicit. 

fixes #2226

### CODE REVIEW

File: sentry-ruby/lib/sentry/configuration.rb [hunk 1]
```diff
@@ -478,10 +478,14 @@ def profiles_sample_rate=(profiles_sample_rate)
       @profiles_sample_rate = profiles_sample_rate
     end
 
+    def event_building_allowed?
```
Comment (sl0thentr0py) [inline sentry-ruby/lib/sentry/configuration.rb:481]: @st0012 lmk if you have a better name for this :)

File: sentry-ruby/spec/sentry/configuration_spec.rb [hunk 2]
```diff
@@ -271,10 +271,21 @@
     end
   end
 
-  describe "#sending_allowed?" do
```
Comment (st0012) [inline sentry-ruby/spec/sentry/configuration_spec.rb:274]: Shouldn't we still have tests for this method?

File: sentry-ruby/lib/sentry/configuration.rb (hunk 1 above)
Comment (st0012) [reply sentry-ruby/lib/sentry/configuration.rb:481]: I feel this should be called `sending_allowed?` and the original `sending_allowed?` should be something like `sending_to_sentry?`

**Comment by sandstrom** [comment]
Just curious, is this something that will be merged soon?

We've tried out Spotlight, but with this bug it's also caused all dev events to flow from developer machines to Sentry, with no easy way to turn it off.

Would be great for us if this could be merged!

cc @sl0thentr0py @st0012

**Comment by sl0thentr0py** [comment]
sorry slipped through the cracks

**Review by szokeasaurusrex — APPROVED** [review]
stamp
