### PR TITLE
[rails] support string errors in error reporter

### LINKED ISSUE #2460: Using `ActiveSupport::ErrorReporter` with `capture_message`
I'm sorry if it already has been discussed, I couldn't find any info on this topic. `sentry-rails` has built-in integration with ActiveSupport's `ErrorReporter` which allows to report exceptions with service-agnostic `Rails.error` API. Reporting exceptions works fine, but surprisingly it does not work (AFAIK) with sentry's message capturing feature.

It seems like there's no restriction on reported object's type from AS' side; `Rails.error.report("foobar")` propagates message to `capture_exception` where it fails with "ArgumentError: expect the argument to be a Exception, got String" exception.

I'm curious if it's possible to extend sentry's subscriber to propagate strings to `capture_message`? Is there a reason it's not implemented yet?

### PR DESCRIPTION
**Pull request by solnic**
Closes #2460

### CODE REVIEW

File: sentry-rails/lib/sentry/rails/error_subscriber.rb [hunk 1]
```diff
@@ -27,7 +27,16 @@ def report(error, handled:, severity:, context:, source: nil)
...
-        Sentry::Rails.capture_exception(error, level: severity, contexts: { "rails.error" => context }, tags: tags, hint: hint)
+        options = { level: severity, contexts: { "rails.error" => context }, tags: tags, hint: hint }
+
+        case error
+        when String
+          Sentry::Rails.capture_message(error, **options)
+        when Exception
+          Sentry::Rails.capture_exception(error, **options)
+        else
+          raise ArgumentError, "Expected an Exception or a String, got: #{error.inspect}"
```
Comment (sl0thentr0py) [inline sentry-rails/lib/sentry/rails/error_subscriber.rb:38]: we should not raise inside the SDK, let's use `log_debug` here

**Review by sl0thentr0py — CHANGES_REQUESTED** [review]

File: sentry-rails/lib/sentry/rails/error_subscriber.rb (hunk 1 above)
Comment (solnic) [reply sentry-rails/lib/sentry/rails/error_subscriber.rb:38]: @sl0thentr0py hmm, what's the best way of accessing logger though? I can see that the helper is defined in the LoggingHelper, but not sure which object I should use for logging, or if I should include that helper in the ErrorSubscriber?

Comment (sl0thentr0py) [reply sentry-rails/lib/sentry/rails/error_subscriber.rb:38]: yes you can just include it

Comment (solnic) [reply sentry-rails/lib/sentry/rails/error_subscriber.rb:38]: @sl0thentr0py sorry, but could you tell me how I should configure the logger so that I could do something like this in the spec:

```ruby
expect {
          Rails.error.report(312, severity: :info, context: { foo: "bar" })
        }.to output(/Expected an Exception or a String, got: 312/).to_stdout
```

? Including the helper is not enough as it expects `@logger` which is not set on the ErrorReporter.

Comment (sl0thentr0py) [reply sentry-rails/lib/sentry/rails/error_subscriber.rb:38]: yes for that you need the instance var, but you can also use `Sentry.configuration.logger` directly
