### PR TITLE
Fix sentry-delayed_job: respect custom max_attempts

### LINKED ISSUE #2076: Delayed job plugin misses  errors from jobs with custom max_attempts
### Issue Description

The Delayed Job plugin sends errors, to Sentry, after retries when the default max_attempt is applied.

However, when the job defines a custom max_attempts, the delayed job plugin fails to observe the last attempt and misses sending the error to Sentry

Suggested Fix for [delayed-job plugin](https://github.com/getsentry/sentry-ruby/blob/7764384e07bf7927c5a9a9d4c19688e9c1b11f56/sentry-delayed_job/lib/sentry/delayed_job/plugin.rb#L85)
```
      def self.report?(job)
        return true unless Sentry.configuration.delayed_job.report_after_job_retries

        # We use the predecessor because the job's attempts haven't been increased to the new
        # count at this point.
        job.attempts >= job.max_attempts.pred || Delayed::Worker.max_attempts.pred
      end
```

### Reproduction Steps

1. Created a class that would error, with custom max_attempts
2. Enqueued the class 
3. Verified the error was not sent to Sentry

### Expected Behavior

1. Created a class that would error, with custom max_attempts of 2
2. Enqueued the class 
3. Verified the error WAS sent to Sentry

### Actual Behavior

The error was never sent to Sentry because the job's max_attempts were less than the default max attempts.

### Ruby Version

3.1.2

### SDK Version

5.7.0

### Integration and Its Version

DelayedJob

### Sentry Config
```
# frozen_string_literal: true

return unless Rails.application.secrets.sentry_dsn.present?

require "non_notifiable_error"
require "redis_connection"

Sentry.init do |config|
  config.dsn = Rails.application.secrets.sentry_dsn
  config.breadcrumbs_logger = [:active_support_logger, :http_logger]

  config.environment = Rails.application.secrets.release_stage
  config.release = Rails.application.secrets.commit_tag
  config.excluded_exceptions += [NonNotifiableError, ActionController::BadRequest, Mime::Type::InvalidMimeType]
  config.delayed_job.report_after_job_retries = true
  config.sidekiq.report_after_job_retries = true

  config.traces_sampler = lambda do |sampling_context|
    unless sampling_context[:parent_sampled].nil?
      next sampling_context[:parent_sampled]
    end
    transaction_context = sampling_context[:transaction_context]

    op = transaction_context[:op]
    transaction_name = transaction_context[:name]

    case op
    when /http/
      # for Rails applications, transaction_name would be the request's path (env["PATH_INFO"]) instead of "Controller#action"
      case transaction_name
      when /health/
        0.0
      when %r(internal/metrics)
        0.0
      else
        Rails.application.secrets.sentry_traces_sample_rate
      end
    end
  end

  config.before_send = lambda do |event, hint|
    backtrace = hint[:exception]&.backtrace

    if backtrace
      code_teams_team = CodeOwners.for_backtrace(backtrace)
      if code_teams_team
        event.tags[:code_owner] = code_teams_team.name
      end
    else
      Rails.logger.info(msg: "Could not log backtrace", error: hint[:exception].to_s)
    end

    ErrorReporter.confirm_within_limit_and_report(event)
  end
end

if Rails.application.secrets.release_stage == "preview"
  Sentry.set_tags(preview: Rails.application.secrets.sub_domain_suffix || "missing")
end
```

### PR DESCRIPTION
**Pull request by natikgadzhi**
## Summary

- Fixes #2076:
- Applies the fix that @claireannecotter proposed, ensuring it's safe.
- Adds specs and the CHANGELOG entry.

/cc @sl0thentr0py are you tired of me yet?

### CODE REVIEW

File: sentry-delayed_job/spec/sentry/delayed_job_spec.rb [hunk 1]
```diff
@@ -143,6 +143,22 @@ def self.class_do_nothing
...
       end
 
+      # Default max_attemps is defined on Delayed::Worker.max_attempts == 25.
+      # However, users can customize max_attempts on the job class, and DelayedJob
+      # will respect that.
+      # Sentry needs to report an exception if report_after_retries is true and
+      # custom job-level max_attempts is reached.
+      # See https://github.com/collectiveidea/delayed_job#custom-jobs
+      it "reports exception after the job's custom max_attempts" do
+        enqueued_job.update(attempts:2)
```
Comment (st0012) [inline sentry-delayed_job/spec/sentry/delayed_job_spec.rb:153]:
```suggestion
        enqueued_job.update(attempts: 2)
```

**Review by st0012 — APPROVED** [review]
Let's add a changelog entry for this?

**Comment by natikgadzhi** [comment]
@st0012 yep, I've added it and didn't push it up 🤦🏼. Fixed.
