### PR TITLE
Prevent starting Vernier in nested transactions

### LINKED ISSUE #2525: NoMethodError: undefined method '_stack_table' for nil
### Issue Description

Disclaimer: I am very unfamiliar with profiling, for context I am plugging Sentry to a new side project and saw this new feature and decided to enable it.

I just setup `vernier` for my profiling on a new, simple Rails app. My app runs background jobs (via `solid_queue`), including cron jobs. Some of the cron jobs (not all of them) return this internal error from Vernier. Weirdly, trying to re-run them from MissionControl, again, sometimes it fails, sometimes it passes.

It is not blocking anything on my side at the moment. I will monitor this to share some numbers, but if you already have some questions or ideas at what I should look at to help, let me know.

Note that this error is _not_ reported by Sentry in the issue tracker.

Example of a full stack trace:
```
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-ruby-5.22.1/lib/sentry/vernier/output.rb:85:in 'Sentry::Vernier::Output#stack_table_hash'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-ruby-5.22.1/lib/sentry/vernier/output.rb:57:in 'Sentry::Vernier::Output#frames'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-ruby-5.22.1/lib/sentry/vernier/output.rb:22:in 'Sentry::Vernier::Output#to_h'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-ruby-5.22.1/lib/sentry/vernier/profiler.rb:99:in 'Sentry::Vernier::Profiler#to_hash'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-ruby-5.22.1/lib/sentry/transaction_event.rb:63:in 'Sentry::TransactionEvent#populate_profile'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-ruby-5.22.1/lib/sentry/transaction_event.rb:40:in 'Sentry::TransactionEvent#initialize'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-ruby-5.22.1/lib/sentry/client.rb:174:in 'Class#new'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-ruby-5.22.1/lib/sentry/client.rb:174:in 'Sentry::Client#event_from_transaction'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-ruby-5.22.1/lib/sentry/transaction.rb:263:in 'Sentry::Transaction#finish'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-rails-5.22.1/lib/sentry/rails/active_job.rb:66:in 'Sentry::Rails::ActiveJobExtensions::SentryReporter.finish_sentry_transaction'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-rails-5.22.1/lib/sentry/rails/active_job.rb:47:in 'block in Sentry::Rails::ActiveJobExtensions::SentryReporter.record'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-ruby-5.22.1/lib/sentry/hub.rb:59:in 'Sentry::Hub#with_scope'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-ruby-5.22.1/lib/sentry-ruby.rb:396:in 'Sentry.with_scope'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-rails-5.22.1/lib/sentry/rails/active_job.rb:26:in 'Sentry::Rails::ActiveJobExtensions::SentryReporter.record'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/sentry-rails-5.22.1/lib/sentry/rails/active_job.rb:10:in 'Sentry::Rails::ActiveJobExtensions#perform_now'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/activejob-8.0.1/lib/active_job/execution.rb:29:in 'block in ActiveJob::Execution::ClassMethods#execute'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:120:in 'block in ActiveSupport::Callbacks#run_callbacks'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/activejob-8.0.1/lib/active_job/railtie.rb:95:in 'block (4 levels) in <class:Railtie>'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.1/lib/active_support/reloader.rb:77:in 'block in ActiveSupport::Reloader.wrap'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.1/lib/active_support/execution_wrapper.rb:87:in 'ActiveSupport::ExecutionWrapper.wrap'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.1/lib/active_support/reloader.rb:74:in 'ActiveSupport::Reloader.wrap'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/activejob-8.0.1/lib/active_job/railtie.rb:94:in 'block (3 levels) in <class:Railtie>'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:129:in 'BasicObject#instance_exec'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:129:in 'block in ActiveSupport::Callbacks#run_callbacks'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.1/lib/active_support/callbacks.rb:140:in 'ActiveSupport::Callbacks#run_callbacks'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/activejob-8.0.1/lib/active_job/execution.rb:27:in 'ActiveJob::Execution::ClassMethods#execute'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solid_queue-1.1.2/app/models/solid_queue/claimed_execution.rb:95:in 'SolidQueue::ClaimedExecution#execute'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solid_queue-1.1.2/app/models/solid_queue/claimed_execution.rb:61:in 'SolidQueue::ClaimedExecution#perform'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solid_queue-1.1.2/lib/solid_queue/pool.rb:23:in 'block (2 levels) in SolidQueue::Pool#post'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.1/lib/active_support/execution_wrapper.rb:91:in 'ActiveSupport::ExecutionWrapper.wrap'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solid_queue-1.1.2/lib/solid_queue/app_executor.rb:7:in 'SolidQueue::AppExecutor#wrap_in_app_executor'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solid_queue-1.1.2/lib/solid_queue/pool.rb:22:in 'block in SolidQueue::Pool#post'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in 'block in Concurrent::SafeTaskExecutor#execute'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in 'block in Concurrent::Synchronization::MutexLockableObject#synchronize'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in 'Thread::Mutex#synchronize'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in 'Concurrent::Synchronization::MutexLockableObject#synchronize'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in 'Concurrent::SafeTaskExecutor#execute'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/ivar.rb:170:in 'Concurrent::IVar#safe_execute'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/future.rb:55:in 'block in Concurrent::Future#execute'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in 'Concurrent::RubyThreadPoolExecutor::Worker#run_task'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in 'block (3 levels) in Concurrent::RubyThreadPoolExecutor::Worker#create_worker'
<internal:kernel>:168:in 'Kernel#loop'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in 'block (2 levels) in Concurrent::RubyThreadPoolExecutor::Worker#create_worker'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in 'Kernel#catch'
/Users/pierreloic/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in 'block in Concurrent::RubyThreadPoolExecutor::Worker#create_worker'
```

### Reproduction Steps

I'm having a hard time to reproduce, because it is not systematic.

Here is my Gemfile.lock:
```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (8.0.1)
      actionpack (= 8.0.1)
      activesupport (= 8.0.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
      zeitwerk (~> 2.6)
    actionmailbox (8.0.1)
      actionpack (= 8.0.1)
      activejob (= 8.0.1)
      activerecord (= 8.0.1)
      activestorage (= 8.0.1)
      activesupport (= 8.0.1)
      mail (>= 2.8.0)
    actionmailer (8.0.1)
      actionpack (= 8.0.1)
      actionview (= 8.0.1)
      activejob (= 8.0.1)
      activesupport (= 8.0.1)
      mail (>= 2.8.0)
      rails-dom-testing (~> 2.2)
    actionpack (8.0.1)
      actionview (= 8.0.1)
      activesupport (= 8.0.1)
      nokogiri (>= 1.8.5)
      rack (>= 2.2.4)
      rack-session (>= 1.0.1)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
      useragent (~> 0.16)
    actiontext (8.0.1)
      actionpack (= 8.0.1)
      activerecord (= 8.0.1)
      activestorage (= 8.0.1)
      activesupport (= 8.0.1)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (8.0.1)
      activesupport (= 8.0.1)
      builder (~> 3.1)
      erubi (~> 1.11)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
    activejob (8.0.1)
      activesupport (= 8.0.1)
      globalid (>= 0.3.6)
    activemodel (8.0.1)
      activesupport (= 8.0.1)
    activerecord (8.0.1)
      activemodel (= 8.0.1)
      activesupport (= 8.0.1)
      timeout (>= 0.4.0)
    activestorage (8.0.1)
      actionpack (= 8.0.1)
      activejob (= 8.0.1)
      activerecord (= 8.0.1)
      activesupport (= 8.0.1)
      marcel (~> 1.0)
    activesupport (8.0.1)
      base64
      benchmark (>= 0.3)
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.3.1)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
      logger (>= 1.4.2)
      minitest (>= 5.1)
      securerandom (>= 0.3)
      tzinfo (~> 2.0, >= 2.0.5)
      uri (>= 0.13.1)
    ast (2.4.2)
    base64 (0.2.0)
    benchmark (0.4.0)
    bigdecimal (3.1.9)
    bindex (0.8.1)
    blazer (3.1.0)
      activerecord (>= 6.1)
      chartkick (>= 5)
      csv
      railties (>= 7)
      safely_block (>= 0.4)
    bootsnap (1.18.4)
      msgpack (~> 1.2)
    brakeman (7.0.0)
      racc
    builder (3.3.0)
    chartkick (5.1.2)
    concurrent-ruby (1.3.5)
    connection_pool (2.5.0)
    crass (1.0.6)
    csv (3.3.2)
    date (3.4.1)
    debug (1.10.0)
      irb (~> 1.10)
      reline (>= 0.3.8)
    drb (2.2.1)
    erubi (1.13.1)
    et-orbi (1.2.11)
      tzinfo
    fugit (1.11.1)
      et-orbi (~> 1, >= 1.2.11)
      raabro (~> 1.4)
    globalid (1.2.1)
      activesupport (>= 6.1)
    i18n (1.14.7)
      concurrent-ruby (~> 1.0)
    importmap-rails (2.1.0)
      actionpack (>= 6.0.0)
      activesupport (>= 6.0.0)
      railties (>= 6.0.0)
    io-console (0.8.0)
    irb (1.15.1)
      pp (>= 0.6.0)
      rdoc (>= 4.0.0)
      reline (>= 0.4.2)
    jbuilder (2.13.0)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    json (2.9.1)
    language_server-protocol (3.17.0.3)
    logger (1.6.5)
    loofah (2.24.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.4)
    mini_mime (1.1.5)
    minitest (5.25.4)
    mission_control-jobs (1.0.1)
      actioncable (>= 7.1)
      actionpack (>= 7.1)
      activejob (>= 7.1)
      activerecord (>= 7.1)
      importmap-rails (>= 1.2.1)
      irb (~> 1.13)
      railties (>= 7.1)
      stimulus-rails
      turbo-rails
    msgpack (1.7.5)
    net-imap (0.5.5)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.2)
      timeout
    net-smtp (0.5.0)
    nio4r (2.7.4)
    nokogiri (1.18.2-aarch64-linux-gnu)
      racc (~> 1.4)
    nokogiri (1.18.2-aarch64-linux-musl)
      racc (~> 1.4)
    nokogiri (1.18.2-arm-linux-gnu)
      racc (~> 1.4)
    nokogiri (1.18.2-arm-linux-musl)
      racc (~> 1.4)
    nokogiri (1.18.2-arm64-darwin)
      racc (~> 1.4)
    nokogiri (1.18.2-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.18.2-x86_64-linux-gnu)
      racc (~> 1.4)
    nokogiri (1.18.2-x86_64-linux-musl)
      racc (~> 1.4)
    parallel (1.26.3)
    parser (3.3.7.0)
      ast (~> 2.4.1)
      racc
    pg (1.5.9)
    pghero (3.6.1)
      activerecord (>= 6.1)
    pp (0.6.2)
      prettyprint
    prettyprint (0.2.0)
    propshaft (1.1.0)
      actionpack (>= 7.0.0)
      activesupport (>= 7.0.0)
      rack
      railties (>= 7.0.0)
    psych (5.2.3)
      date
      stringio
    puma (6.5.0)
      nio4r (~> 2.0)
    raabro (1.4.0)
    racc (1.8.1)
    rack (3.1.8)
    rack-session (2.1.0)
      base64 (>= 0.1.0)
      rack (>= 3.0.0)
    rack-test (2.2.0)
      rack (>= 1.3)
    rackup (2.2.1)
      rack (>= 3)
    rails (8.0.1)
      actioncable (= 8.0.1)
      actionmailbox (= 8.0.1)
      actionmailer (= 8.0.1)
      actionpack (= 8.0.1)
      actiontext (= 8.0.1)
      actionview (= 8.0.1)
      activejob (= 8.0.1)
      activemodel (= 8.0.1)
      activerecord (= 8.0.1)
      activestorage (= 8.0.1)
      activesupport (= 8.0.1)
      bundler (>= 1.15.0)
      railties (= 8.0.1)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.2)
      loofah (~> 2.21)
      nokogiri (>= 1.15.7, != 1.16.7, != 1.16.6, != 1.16.5, != 1.16.4, != 1.16.3, != 1.16.2, != 1.16.1, != 1.16.0.rc1, != 1.16.0)
    railties (8.0.1)
      actionpack (= 8.0.1)
      activesupport (= 8.0.1)
      irb (~> 1.13)
      rackup (>= 1.0.0)
      rake (>= 12.2)
      thor (~> 1.0, >= 1.2.2)
      zeitwerk (~> 2.6)
    rainbow (3.1.1)
    rake (13.2.1)
    rdoc (6.11.0)
      psych (>= 4.0.0)
    regexp_parser (2.10.0)
    reline (0.6.0)
      io-console (~> 0.5)
    rubocop (1.71.0)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.3.0.2)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 2.9.3, < 3.0)
      rubocop-ast (>= 1.36.2, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 4.0)
    rubocop-ast (1.37.0)
      parser (>= 3.3.1.0)
    rubocop-minitest (0.36.0)
      rubocop (>= 1.61, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-performance (1.23.1)
      rubocop (>= 1.48.1, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-rails (2.29.1)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.52.0, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-rails-omakase (1.0.0)
      rubocop
      rubocop-minitest
      rubocop-performance
      rubocop-rails
    ruby-progressbar (1.13.0)
    safely_block (0.4.1)
    securerandom (0.4.1)
    sentry-rails (5.22.1)
      railties (>= 5.0)
      sentry-ruby (~> 5.22.1)
    sentry-ruby (5.22.1)
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.0.2)
    solid_queue (1.1.2)
      activejob (>= 7.1)
      activerecord (>= 7.1)
      concurrent-ruby (>= 1.3.1)
      fugit (~> 1.11.0)
      railties (>= 7.1)
      thor (~> 1.3.1)
    stimulus-rails (1.3.4)
      railties (>= 6.0.0)
    stringio (3.1.2)
    strong_migrations (2.1.0)
      activerecord (>= 6.1)
    tailwindcss-rails (3.3.1)
      railties (>= 7.0.0)
      tailwindcss-ruby (~> 3.0)
    tailwindcss-ruby (3.4.17-aarch64-linux)
    tailwindcss-ruby (3.4.17-arm-linux)
    tailwindcss-ruby (3.4.17-arm64-darwin)
    tailwindcss-ruby (3.4.17-x86_64-darwin)
    tailwindcss-ruby (3.4.17-x86_64-linux)
    thor (1.3.2)
    thruster (0.1.10)
    thruster (0.1.10-aarch64-linux)
    thruster (0.1.10-arm64-darwin)
    thruster (0.1.10-x86_64-darwin)
    thruster (0.1.10-x86_64-linux)
    timeout (0.4.3)
    turbo-rails (2.0.11)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    unicode-display_width (3.1.4)
      unicode-emoji (~> 4.0, >= 4.0.4)
    unicode-emoji (4.0.4)
    uri (1.0.2)
    useragent (0.16.11)
    vernier (1.5.0)
    web-console (4.2.1)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    websocket-driver (0.7.7)
      base64
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    zeitwerk (2.7.1)

PLATFORMS
  aarch64-linux
  aarch64-linux-gnu
  aarch64-linux-musl
  arm-linux
  arm-linux-gnu
  arm-linux-musl
  arm64-darwin
  x86_64-darwin
  x86_64-linux
  x86_64-linux-gnu
  x86_64-linux-musl

DEPENDENCIES
  blazer
  bootsnap
  brakeman
  debug
  importmap-rails
  jbuilder
  mission_control-jobs
  pg (~> 1.1)
  pghero
  propshaft
  puma (>= 5.0)
  rails (~> 8.0.1)
  rubocop-rails-omakase
  sentry-rails
  sentry-ruby
  solid_queue
  stimulus-rails
  strong_migrations
  tailwindcss-rails
  thruster
  turbo-rails
  tzinfo-data
  vernier
  web-console

RUBY VERSION
   ruby 3.4.1p0

BUNDLED WITH
   2.6.3
```

### Expected Behavior

Not having this vernier internal error

### Actual Behavior

Getting sporadically this error, in dev and in prod.

### Ruby Version

3.4.1

### SDK Version

5.22.1

### Integration and Its Version

Rails 8.0.1 + Solid Queue as ActiveJob backend

### Sentry Config

```ruby
Sentry.init do |config|
  config.dsn = Rails.application.credentials.dig(:sentry, :dsn)

  config.breadcrumbs_logger = [ :sentry_logger, :http_logger, :monotonic_active_support_logger ]
  config.debug = true
  config.traces_sample_rate = 1.0
  config.profiler_class = Sentry::Vernier::Profiler
  config.profiles_sample_rate = 1.0
end
```

### PR DESCRIPTION
**Pull request by solnic**
Fixes #2525 

I suspect this will also help with #2457

### CODE REVIEW

File: sentry-ruby/lib/sentry/transaction.rb [hunk 1]
```diff
@@ -257,7 +261,7 @@ def finish(hub: nil, end_timestamp: nil)
         @name = UNLABELD_NAME
       end
 
-      @profiler.stop
+      @hub.stop_profiler!(self)
```
Comment (solnic) [inline sentry-ruby/lib/sentry/transaction.rb:264]: Given that the hub is responsible for starting a profiler, making this change actually felt like an improvement. Transactions are coupled to hub anyway.

**Comment by st0012** [comment]
I think more of profiler related logic can actually be moved out of `Transaction` into `Hub`. I'll suggest some changes later.

**Comment by st0012** [comment]
Something like this?

```diff
diff --git a/sentry-ruby/lib/sentry/hub.rb b/sentry-ruby/lib/sentry/hub.rb
index 788e8902..a1343831 100644
--- a/sentry-ruby/lib/sentry/hub.rb
+++ b/sentry-ruby/lib/sentry/hub.rb
@@ -23,8 +23,17 @@ module Sentry
 
     def start_profiler!(transaction)
       MUTEX.synchronize do
-        transaction.start_profiler!
-        @current_profiler[transaction.__id__] = transaction.profiler
+        return if !@current_profiler.empty?
+        profiler = configuration.profiler_class.new(configuration)
+        profiler.set_initial_sample_decision(transaction.sampled)
+        profiler.start
+        @current_profiler[transaction.__id__] = profiler
+      end
+    end
+
+    def profiler_for(transaction)
+      MUTEX.synchronize do
+        @current_profiler[transaction.__id__]
       end
     end
 
@@ -34,12 +43,6 @@ module Sentry
       end
     end
 
-    def profiler_running?
-      MUTEX.synchronize do
-        !@current_profiler.empty?
-      end
-    end
-
     def new_from_top
       Hub.new(current_client, current_scope)
     end
diff --git a/sentry-ruby/lib/sentry/transaction.rb b/sentry-ruby/lib/sentry/transaction.rb
index 6fc2524b..8fc077e5 100644
--- a/sentry-ruby/lib/sentry/transaction.rb
+++ b/sentry-ruby/lib/sentry/transaction.rb
@@ -56,10 +56,6 @@ module Sentry
     # @return [Hash]
     attr_reader :contexts
 
-    # The Profiler instance for this transaction.
-    # @return [Profiler]
-    attr_reader :profiler
-
     def initialize(
       hub:,
       name: nil,
@@ -86,10 +82,6 @@ module Sentry
       @contexts = {}
       @measurements = {}
 
-      unless @hub.profiler_running?
-        @profiler = @configuration.profiler_class.new(@configuration)
-      end
-
       init_span_recorder
     end
 
@@ -300,13 +292,16 @@ module Sentry
       @contexts[key] = value
     end
 
+    # The Profiler instance for this transaction.
+    # @return [Profiler]
+    def profiler
+      @hub.profiler_for(self)
+    end
+
     # Start the profiler.
     # @return [void]
     def start_profiler!
-      return unless profiler
-
-      profiler.set_initial_sample_decision(sampled)
-      profiler.start
+      @hub.start_profiler!(self)
     end
 
     # These are high cardinality and thus bad
diff --git a/sentry-ruby/spec/sentry/transactions/profiler_spec.rb b/sentry-ruby/spec/sentry/transactions/profiler_spec.rb
index 78bb385b..fb1efd7b 100644
--- a/sentry-ruby/spec/sentry/transactions/profiler_spec.rb
+++ b/sentry-ruby/spec/sentry/transactions/profiler_spec.rb
@@ -21,8 +21,6 @@ RSpec.describe Sentry, 'transactions / profiler', when: [:vernier_installed?, :r
 
       ProfilerTest::Bar.bar
 
-      expect(Sentry.get_current_hub.profiler_running?).to be(true)
-
       expect(parent_transaction.profiler).to_not be_nil
       expect(nested_transaction.profiler).to be_nil
 ```

**Comment by sl0thentr0py** [comment]
ok let's take a step back, is this
* *only* about nested transactions 
* or more generally about not starting Vernier again when it's already running (globally)
  * if this is the problem, isn't it possible to ask Vernier somehow if it's currently recording? I would prefer that over adding more state into the hub to track this stuff

**Comment by solnic** [comment]
> * if this is the problem, isn't it possible to ask Vernier somehow if it's currently recording? I would prefer that over adding more state into the hub to track this stuff

@sl0thentr0py so, I've been grinding my teeth when trying to make it work by checking Vernier. It stores an instance variable called `@collector`, there's no public API to access it, accessing it via instance_variable_get seems to be prone to race conditions. I tried with an approach more or less like this:

```diff
diff --git sentry-ruby/lib/sentry/hub.rb sentry-ruby/lib/sentry/hub.rb
index 788e8902..8f9ed9e0 100644
--- sentry-ruby/lib/sentry/hub.rb
+++ sentry-ruby/lib/sentry/hub.rb
@@ -18,26 +18,6 @@ module Sentry
       first_layer = Layer.new(client, scope)
       @stack = [first_layer]
       @last_event_id = nil
-      @current_profiler = {}
-    end
-
-    def start_profiler!(transaction)
-      MUTEX.synchronize do
-        transaction.start_profiler!
-        @current_profiler[transaction.__id__] = transaction.profiler
-      end
-    end
-
-    def stop_profiler!(transaction)
-      MUTEX.synchronize do
-        @current_profiler.delete(transaction.__id__)&.stop
-      end
-    end
-
-    def profiler_running?
-      MUTEX.synchronize do
-        !@current_profiler.empty?
-      end
     end
 
     def new_from_top
@@ -120,7 +100,7 @@ module Sentry
       sampling_context.merge!(custom_sampling_context)
       transaction.set_initial_sample_decision(sampling_context: sampling_context)
 
-      start_profiler!(transaction)
+      transaction.start_profiler!
 
       transaction
     end
diff --git sentry-ruby/lib/sentry/transaction.rb sentry-ruby/lib/sentry/transaction.rb
index 6fc2524b..591c116c 100644
--- sentry-ruby/lib/sentry/transaction.rb
+++ sentry-ruby/lib/sentry/transaction.rb
@@ -85,10 +85,7 @@ module Sentry
       @effective_sample_rate = nil
       @contexts = {}
       @measurements = {}
-
-      unless @hub.profiler_running?
-        @profiler = @configuration.profiler_class.new(@configuration)
-      end
+      @profiler = @configuration.profiler_class.new(@configuration)
 
       init_span_recorder
     end
@@ -261,7 +258,7 @@ module Sentry
         @name = UNLABELD_NAME
       end
 
-      @hub.stop_profiler!(self)
+      @profiler.stop
 
       if @sampled
         event = hub.current_client.event_from_transaction(self)
diff --git sentry-ruby/lib/sentry/vernier/profiler.rb sentry-ruby/lib/sentry/vernier/profiler.rb
index 2818ae8d..4a2c77ec 100644
--- sentry-ruby/lib/sentry/vernier/profiler.rb
+++ sentry-ruby/lib/sentry/vernier/profiler.rb
@@ -8,13 +8,14 @@ module Sentry
   module Vernier
     class Profiler
       EMPTY_RESULT = {}.freeze
+      MUTEX = Mutex.new
 
-      attr_reader :started, :event_id, :result
+      attr_reader :event_id, :result
 
       def initialize(configuration)
         @event_id = SecureRandom.uuid.delete("-")
 
-        @started = false
+        @vernier_collector = nil
         @sampled = nil
 
         @profiling_enabled = defined?(Vernier) && configuration.profiling_enabled?
@@ -51,38 +52,53 @@ module Sentry
         log("Discarding profile due to sampling decision") unless @sampled
       end
 
-      def start
-        return unless @sampled
-        return if @started
+      def other_vernier_running?
+        MUTEX.synchronize do
+          @vernier_collector && vernier_collector_id != @vernier_collector.__id__
+        end
+      end
 
-        @started = ::Vernier.start_profile
+      def this_vernier_running?
+        MUTEX.synchronize do
+          @vernier_collector && vernier_collector_id == @vernier_collector.__id__
+        end
+      end
 
-        log("Started")
+      def vernier_collector_id
+        Vernier.instance_variable_get(:@collector).__id__ if Vernier.instance_variable_get(:@collector)
+      end
 
-        @started
-      rescue RuntimeError => e
-        # TODO: once Vernier raises something more dedicated, we should catch that instead
-        if e.message.include?("Profile already started")
-          log("Not started since running elsewhere")
-        else
-          log("Failed to start: #{e.message}")
-        end
+      def start
+        return if !@sampled || other_vernier_running?
+
+        @vernier_collector = ::Vernier.start_profile
+
+        log("Started with Vernier collector id: #{vernier_collector_id}")
+        # rescue RuntimeError => e
+        #   # TODO: once Vernier raises something more dedicated, we should catch that instead
+        #   if e.message.include?("Profile already started")
+        #     log("Not started since running elsewhere")
+        #   else
+        #     log("Failed to start: #{e.message}")
+        #   end
+      rescue
+        debugger
       end
 
       def stop
         return unless @sampled
-        return unless @started
 
-        @result = ::Vernier.stop_profile
-        @started = false
+        @result = ::Vernier.stop_profile if this_vernier_running?
 
         log("Stopped")
-      rescue RuntimeError => e
-        if e.message.include?("Profile not started")
-          log("Not stopped since not started")
-        else
-          log("Failed to stop Vernier: #{e.message}")
-        end
+        # rescue RuntimeError => e
+        # if e.message.include?("Profile not started")
+        #   log("Not stopped since not started")
+        # else
+        #   log("Failed to stop Vernier: #{e.message}")
+        # end
+      ensure
+        @vernier_collector = nil
       end
 
       def active_thread_id
diff --git sentry-ruby/spec/sentry/transactions/profiler_spec.rb sentry-ruby/spec/sentry/transactions/profiler_spec.rb
index 78bb385b..5311fac6 100644
--- sentry-ruby/spec/sentry/transactions/profiler_spec.rb
+++ sentry-ruby/spec/sentry/transactions/profiler_spec.rb
@@ -15,19 +15,16 @@ RSpec.describe Sentry, 'transactions / profiler', when: [:vernier_installed?, :r
   end
 
   it 'starts profiler just once inside nested transactions' do
-    10.times do
+    10000.times do
       parent_transaction = Sentry.start_transaction(name: "parent")
       nested_transaction = Sentry.start_transaction(name: "nested")
 
-      ProfilerTest::Bar.bar
-
-      expect(Sentry.get_current_hub.profiler_running?).to be(true)
-
-      expect(parent_transaction.profiler).to_not be_nil
-      expect(nested_transaction.profiler).to be_nil
+      ProfilerTest::Bar::Foo.foo(10)
 
       nested_transaction.finish
       parent_transaction.finish
+
+      expect(parent_transaction.profiler.to_hash).to_not be_empty
     end
   end
 end
diff --git sentry-ruby/spec/support/profiler.rb sentry-ruby/spec/support/profiler.rb
index ee83cc4d..2a8803a1 100644
--- sentry-ruby/spec/support/profiler.rb
+++ sentry-ruby/spec/support/profiler.rb
@@ -3,8 +3,8 @@
 module ProfilerTest
   module Bar
     module Foo
-      def self.foo
-        1e6.to_i.times { 2**2 }
+      def self.foo(count = 1e6.to_i)
+        count.times { 2**2 }
       end
     end
```

...and it just doesn't work. Once we have more than one profile running and they try to interact with Vernier, things become unstable and we end up with errors.

It passes really consistently when it's handled higher-up in the Hub. I also think it's good that we don't create a profiler when it's not going to be used.

It seems to be the simplest thing that can possibly work. Can we just stick to this solution?

**Comment by sl0thentr0py** [comment]
could we ask the Vernier folks what the best way to do this is? Maybe they can expose it officially?

**Comment by solnic** [comment]
hey @jhawthorn any chance you could chime in and help us out with this? Long story short is that we need to prevent our transactions from starting Vernier more than once, and it turned out to be a challenge. I put some guards in this PR that ensure that we do not create more than one Profiler instance, but we'd prefer if we could handle it in the profiler itself. I noticed there's `@collection` set when Vernier is running but based on my tests it looks like checking for that variable is not thread-safe/stable.

**Comment by solnic** [comment]
@sl0thentr0py @st0012 I reverted my attempts at solving it at the transaction level and I still think having hub orchestrate this is the simplest thing to do and it *works*, unlike every other attempt at checking if Vernier is running.

Could you revisit this please? Without fixing this Vernier profiler is not stable so I'd love to get the fix done.

File: sentry-ruby/lib/sentry/hub.rb [hunk 2]
```diff
@@ -8,12 +8,36 @@ module Sentry
...
+    attr_reader :current_profiler
+
     def initialize(client, scope)
       first_layer = Layer.new(client, scope)
       @stack = [first_layer]
       @last_event_id = nil
+      @current_profiler = {}
+    end
+
+    def start_profiler!(transaction)
```
Comment (sl0thentr0py) [inline sentry-ruby/lib/sentry/hub.rb:24]: can you add a docstring saying these are internal methods

**Review by sl0thentr0py — APPROVED** [review]

**Comment by sl0thentr0py** [comment]
and let's please just merge this minimal change, a bigger refactor is not necessary for this very edge case scenario. Hub/profiler etc will change in the future anyway so I don't want us to spend time on refactors.
