### PR TITLE
fix(logs): skip malformed utf-8 messages

### LINKED ISSUE #2773: Invalid UTF-8 for logs
### Issue Description

Sending invalid UTF-8 results in logs not being sent.  Same situation only for logs; previously covered in https://github.com/getsentry/sentry-ruby/issues/2376.

### Reproduction Steps

Send invalid UTF-8 logs.

### Expected Behavior

Should be sent or have better handling.

### Actual Behavior

Instead it fails hard.

### Ruby Version

3.3.0

### SDK Version

6.0

### Integration and Its Version

_No response_

### Sentry Config

_No response_

### PR DESCRIPTION
**Pull request by solnic**
Fixes #2773

### CODE REVIEW

File: sentry-ruby/lib/sentry/utils/encoding_helper.rb [hunk 1]
```diff
@@ -3,6 +3,8 @@
 module Sentry
   module Utils
     module EncodingHelper
+      EMPTY_STRING = ""
```
Comment (chaadow) [inline sentry-ruby/lib/sentry/utils/encoding_helper.rb:6]: hi, just wondering where this constant is used?

Comment (solnic) [reply sentry-ruby/lib/sentry/utils/encoding_helper.rb:6]: right we no longer need this, thanks I'll remove it!
