### PR TITLE
Optimize LogEvent to reduce memory consumption

### LINKED ISSUE #2641: Increase Memory usage in Logging
### Issue Description

We're trying out logging with Sentry - Firstly as a partial log-sink for Rails logs. Rails is not supported officially yet, but our initial attempts has shown somewhat highly increased memory in preprod environments. Is this something you're aware of, or something that we/I should dig into?

### Reproduction Steps

Add "mirrored" logging to for config.logger in Rails initializer:

```ruby
dual_logger = Class.new(Logger) do
    LOGGER_TO_SENTRY = {
      Logger::Severity::DEBUG => :debug,
      Logger::Severity::INFO => :info,
      Logger::Severity::WARN => :warning,
      Logger::Severity::ERROR => :error,
      Logger::Severity::FATAL => :fatal,
      Logger::Severity::UNKNOWN => :fatal
    }
    def initialize(input)
      super(input)

      @stdout_logger = ActiveSupport::TaggedLogging.new(ActiveSupport::Logger.new(input))
      @stdout_logger.level = Logger::DEBUG
    end

    def add(severity, message = nil, progname = nil)
      message ||= yield if block_given?

      return true if message.nil? || message.empty?

      @stdout_logger.add(severity, message, progname)
      Sentry.logger.log(LOGGER_TO_SENTRY[severity], message, parameters: []) if severity >= Logger::Severity::INFO
    end
  end

  Rails.logger = dual_logger.new($stdout)
```

This is not exactly production-ready, or pretty; But solves the issue of logging to default STDOUT logger, as well as `Sentry.logger`.

And while this DOES work - Memory increases massively (~40% in our test-env on our application until OOM in Kubernetes).

I have not determined if it's leaking, or if it's just fragmenting a lot more, and leaving huge empty pages etc.

### Expected Behavior

Memory can increase, but should not increase this much for logging.

### Actual Behavior

Memory increases until OOM

### Ruby Version

3.4.3

### SDK Version

5.24.0

### Integration and Its Version

ruby, rails, sidekiq

### Sentry Config

```ruby
  require 'p2b/sentry/active_record_instantiation_subscriber'

  Sentry.init do |config|
    config.dsn = 'https://onprem.sentry/...'
    config.enabled_environments = %w[production staging]
    config.skip_rake_integration = true
    config.send_default_pii = true
    config.send_modules = false

    config.traces_sample_rate = Rails.env.production? ? 0.4 : 1
    config.profiles_sample_rate = Rails.env.production? ? 0.2 : 1
    if Rails.env.staging?
      config.debug = true
      config.enable_logs = true
      config.sdk_logger.level = Logger::Severity::DEBUG
    else
      config.sdk_logger.level = Logger::Severity::WARN
    end

    config.enabled_patches += [:sidekiq_cron, :excon, :redis, :graphql]
    # Hold that thought. Would be nice to have this as nested spans. How though.
    config.rails.tracing_subscribers << P2b::Sentry::ActiveRecordInstantiationSubscriber
    config.before_send = lambda do |event, hint|
      if hint[:exception].is_a?(ActiveRecord::RecordInvalid)
        begin
          event.set_tags(e.record.errors.to_hash.to_h { ["errors.#{_1}", [*_2].join(';')] })
        rescue
          # This is ok. Don't error out if we can't set tags.
        end
      end

      event
    end
  end
```

### PR DESCRIPTION
**Pull request by solnic**
## Current status

```
Git SHA      Branch     Iter     Allocated    Retained     Alloc Mem    Ret Mem     
------------------------------------------------------------------------------------------
213558f3     master     100,000  9,681,713    1,395,346    921.32 MB    217.9 MB    
cafd4cdc     2641-incre 100,000  2,920,177    1,598,060    445.48 MB    285.83 MB   

=== Performance Trends ===

Comparing latest (cafd4cdc) vs baseline (213558f3):

Object Allocation: 📉 -69.84% (decrease)
Object Retention: 📈 +14.53% (increase)
Memory Usage: 📉 -51.65% (decrease)

Memory per iteration:
  Baseline: 9.43 KB
  Latest:   4.56 KB
  Change:   📉 -51.65% (decrease)

=== Recent Commits ===

213558f3 (2025-06-09 12:15)
  [sentry-ruby] fix and improve spec suite setup (#2640)
  Memory: 921.32 MB allocated, 217.9 MB retained

cafd4cdc (2025-06-09 12:15)
  Update CHANGELOG
  Memory: 445.48 MB allocated, 285.83 MB retained
```

Closes #2641

### CODE REVIEW

File: sentry-ruby/lib/sentry/log_event.rb [hunk 1]
```diff
@@ -123,17 +123,15 @@ def attribute_hash(value)
       { value: value, type: value_type(value) }
     end
 
+    VALUE_TYPES = Hash.new("string").merge!({
```
Comment (dentarg) [inline sentry-ruby/lib/sentry/log_event.rb]: Gotta be careful when using the [default value](https://docs.ruby-lang.org/en/3.4/Hash.html#class-Hash-label-Default+Values)
```ruby
$ irb
irb(main):001> a = Hash.new("string")
=> {}
irb(main):002> a["foo"]
=> "string"
irb(main):003> a["bar"] << "bar"
=> "stringbar"
irb(main):004> a["foo"]
=> "stringbar"
```

Comment (sl0thentr0py) [reply sentry-ruby/lib/sentry/log_event.rb]: @solnic 🙏

Comment (solnic) [reply sentry-ruby/lib/sentry/log_event.rb]: @dentarg @sl0thentr0py I believe we're good since there's frozen string literals magic comment at the top of this file.
