### PR TITLE
Gracefully fail on malformed utf-8 breadcrumb message

### LINKED ISSUE #2376: Invalid UTF-8 in breadcrumb messages cause events to not be sent
### Issue Description

Sometimes breadcrumbs with a message that is not valid UTF-8 is generated (for example when using libvips) which results in the transaction not being sent.
```
Event sending failed: source sequence is illegal/malformed utf-8
~/ruby/3.2.4/lib/ruby/3.2.0/json/common.rb:312:in `generate'
~/ruby/3.2.4/lib/ruby/3.2.0/json/common.rb:312:in `generate'
~/ruby/gems/sentry-ruby-5.17.3/lib/sentry/envelope.rb:39:in `to_s'
~/ruby/gems/sentry-ruby-5.17.3/lib/sentry/envelope.rb:43:in `serialize'
~/ruby/gems/sentry-ruby-5.17.3/lib/sentry/transport.rb:74:in `block in serialize_envelope'
~/ruby/gems/sentry-ruby-5.17.3/lib/sentry/transport.rb:73:in `each'
~/ruby/gems/sentry-ruby-5.17.3/lib/sentry/transport.rb:73:in `serialize_envelope'
~/ruby/gems/sentry-ruby-5.17.3/lib/sentry/transport.rb:61:in `send_envelope'
~/ruby/gems/sentry-ruby-5.17.3/lib/sentry/transport.rb:51:in `send_event'
~/ruby/gems/sentry-ruby-5.17.3/lib/sentry/client.rb:192:in `send_event'
~/ruby/gems/sentry-ruby-5.17.3/lib/sentry/client.rb:254:in `block in dispatch_background_event'
~/ruby/gems/sentry-ruby-5.17.3/lib/sentry/background_worker.rb:76:in `_perform'
~/ruby/gems/sentry-ruby-5.17.3/lib/sentry/background_worker.rb:56:in `block in perform'
```

Related issues include #1992 and #1911, the difference here is that the malformed UTF-8 is present in the breadcrumb messages and not in redis keys or spans. If possible, it would be great with a check that detects and handles malformed UTF-8 across the entire transaction event.

### Reproduction Steps

```rb
e = Sentry::Event.new(configuration: Sentry.configuration)
b = Sentry::BreadcrumbBuffer.new
b.record(Sentry::Breadcrumb.new(message: "\x76\xab\x99\xb5"))
e.breadcrumbs = b

Sentry.send_event(e, {})
```

### Expected Behavior

The transaction event is sent

### Actual Behavior

`Event sending failed: source sequence is illegal/malformed utf-8`

### Ruby Version

3.2.0

### SDK Version

5.17.3

### Integration and Its Version

Rails 7.0.8

### Sentry Config

```rb
Sentry.init do |config|
  # ...
  config.traces_sample_rate = 1.0
  config.breadcrumbs_logger = [:sentry_logger, :monotonic_active_support_logger]
end
```

### PR DESCRIPTION
**Pull request by sl0thentr0py**
closes #2376

### CODE REVIEW

File: sentry-ruby/lib/sentry/breadcrumb.rb [hunk 1]
```diff
@@ -47,7 +47,7 @@ def to_hash
     # @param message [String]
     # @return [void]
     def message=(message)
-      @message = message ? message.byteslice(0..Event::MAX_MESSAGE_SIZE_IN_BYTES) : ""
+      @message = message && Utils::EncodingHelper.valid_utf_8?(message) ? message.byteslice(0..Event::MAX_MESSAGE_SIZE_IN_BYTES) : ""
```
Comment (szokeasaurusrex) [inline sentry-ruby/lib/sentry/breadcrumb.rb:50]: Perhaps, we might want to log a debug message if the message is not UTF-8?

Just something to consider, feel free to ignore me here :)

**Review by szokeasaurusrex — APPROVED** [review]
