### PR TITLE
[rails] improve AR tracing performance

### LINKED ISSUE #2595: sentry-rails 5.23.0 ActiveRecord overhead
### Issue Description

sentry-rails 5.23.0 seems to make active record much slower.

### Reproduction Steps

I monitor things with ScoutAPM.

- My baseline is ruby 3.1.7 with YJIT off with `sentry-rails` 5.12.0, my rails application's ActiveRecord time for each request is ~13ms.
- Upgrade to ruby 3.4.2 with YJIT on, ActiveRecord time for each request is ~10ms. `sentry-rails` is still at 5.12.0 so stacktrace doesn't work.
- Upgrade `sentry-rails` to  5.23.0, ActiveRecord time for each request is ~15ms.

I have repeated this a few times and get similar results.

### Expected Behavior

Sentry doesn't add too much overhead to my application's response time.

### Actual Behavior

My response time is slower with `sentry-rails` 5.23.0

### Ruby Version

3.4.2

### SDK Version

5.23.0

### Integration and Its Version

Rails

### Sentry Config

```ruby
Sentry.init do |config|
  config.dsn = ...
  config.breadcrumbs_logger = %i[active_support_logger http_logger]
  config.include_local_variables = true
  config.send_modules = false

  config.enabled_environments = %w[staging production]

  config.excluded_exceptions += %w[SystemExit] if [1, "1", "yes", true, "true"].include?(ENV["IS_JOBS"])
  config.excluded_exceptions += %w[Google::Cloud::AbortedError]

  config.release = ENV["RELEASE_VERSION"]
end

```

### PR DESCRIPTION
**Pull request by solnic**
After introducing `enable_db_query_source` in Rails that's enabled by default ActiveRecord tracing may have potentially became slower, or much slower, depending on the use cases. I believe this is the main culprit causing #2595.

This PR optimizes how query source information is obtained by:

1) Replacing re-parsing of source line and instantiating `Sentry::Backtrace::Line` manually based on the location object that we already have
2) *Caching* instantiated line objects

This makes a significant difference according to various benchmarks I ran:

## master - disabled `enable_db_query_source` vs enabled

```
Warming up --------------------------------------
            disabled     1.000  i/100ms
enabled, threshold=0ms
                         1.000  i/100ms
Calculating -------------------------------------
            disabled      1.344  (± 0.0%) i/s -      7.000 
enabled, threshold=0ms
                          0.718  (± 0.0%) i/s -      4.000  in   5.579486s

Comparison:
            disabled:        1.3 i/s
enabled, threshold=0ms:        0.7 i/s - 1.87x slower

Calculating -------------------------------------
            disabled   129.429M memsize (    11.868M retained)
                         1.452M objects (    74.837k retained)
                        50.000  strings (    50.000  retained)
enabled, threshold=0ms
                       490.249M memsize (    12.676M retained)
                         3.118M objects (    84.908k retained)
                        50.000  strings (    50.000  retained)

Comparison:
            disabled:  129429394 allocated
enabled, threshold=0ms:  490249058 allocated - 3.79x more
```

## this PR - same benchmark disabled `enabled_db_query_source` vs enabled

```
± bundle exec ruby benchmarks/db_query_source_benchmark.rb

Warming up --------------------------------------
            disabled     1.000  i/100ms
enabled, threshold=0ms
                         1.000  i/100ms
Calculating -------------------------------------
            disabled      1.269  (± 0.0%) i/s -      7.000  in   5.522006s
enabled, threshold=0ms
                          1.103  (± 0.0%) i/s -      6.000  in   5.454174s

Comparison:
            disabled:        1.3 i/s
enabled, threshold=0ms:        1.1 i/s - 1.15x slower

Calculating -------------------------------------
            disabled   129.869M memsize (    11.893M retained)
                         1.457M objects (    75.050k retained)
                        50.000  strings (    50.000  retained)
enabled, threshold=0ms
                       158.062M memsize (    11.901M retained)
                         1.923M objects (    75.121k retained)
                        50.000  strings (    50.000  retained)

Comparison:
            disabled:  129869394 allocated
enabled, threshold=0ms:  158062090 allocated - 1.22x more
```

This shows a much smaller impact both in terms of execution time and memory usage.

## Rails app benchmarks

I tested this with a simple rails app that just does a bunch of AR queries.

### Low intensity

Screenshot 2025-11-07 at 16 08 37

Screenshot 2025-11-07 at 16 08 27

## High intensity

Screenshot 2025-11-07 at 16 06 54

Screenshot 2025-11-07 at 16 07 46

Closes #2595

### CODE REVIEW

File: sentry-ruby/lib/sentry/backtrace.rb [hunk 1]
```diff
@@ -100,6 +26,52 @@ def self.parse(backtrace, project_root, app_dirs_pattern, &backtrace_cleanup_cal
       new(lines)
     end
 
+    # Thread.each_caller_location is an API added in Ruby 3.2 that doesn't always collect
+    # the entire stack like Kernel#caller or #caller_locations do.
+    #
+    # @see https://github.com/rails/rails/pull/49095 for more context.
+    if Thread.respond_to?(:each_caller_location)
+      def self.source_location(backtrace_cleaner)
```
Comment (sl0thentr0py) [inline sentry-ruby/lib/sentry/backtrace.rb]: nit: don't like that `backtrace_cleaner` needs this dance, what about:
making this method respond to a block and then using a `yield` on line 46 for `cleaned_frame`. That way, we can also get rid of the nested cache map and just have one level.

**Review by sl0thentr0py — CHANGES_REQUESTED** [review]

File: sentry-ruby/lib/sentry/backtrace.rb (hunk 1 above)
Comment (solnic) [reply sentry-ruby/lib/sentry/backtrace.rb]: Like this 63431dbb1aff919b519461ac2747299ddb5b14a5?
